/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linkus;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import com.mongodb.gridfs.GridFS;
import com.mongodb.gridfs.GridFSInputFile;
import java.awt.Color;
import java.io.File;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Akshay
 */
public class Doctor extends javax.swing.JFrame {
    private boolean flag;

    /**
     * Creates new form Main
     */
    public Doctor(String doc_name) {
        initComponents();
        doc_label.setText("Welcome "+doc_name);
        ok_btn.setVisible(false);
        cal.setVisible(false);
        jLabel5.setVisible(false);
        near_medical();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        p_city_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        doc_label = new javax.swing.JLabel();
        abt_us = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        p_id_text = new javax.swing.JTextField();
        p_name = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        p_name_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_addr_text = new javax.swing.JTextArea();
        p_addr = new javax.swing.JLabel();
        p_email = new javax.swing.JLabel();
        p_male = new javax.swing.JRadioButton();
        p_gender = new javax.swing.JLabel();
        p_submit = new javax.swing.JButton();
        p_female = new javax.swing.JRadioButton();
        p_email_text = new javax.swing.JTextField();
        p_email_label = new javax.swing.JLabel();
        p_gender_label = new javax.swing.JLabel();
        p_reset = new javax.swing.JButton();
        p_dob = new javax.swing.JLabel();
        p_phno = new javax.swing.JLabel();
        p_phno_text = new javax.swing.JTextField();
        p_dob_text = new javax.swing.JTextField();
        p_dob_label = new javax.swing.JLabel();
        p_phno_label = new javax.swing.JLabel();
        p_addr_label = new javax.swing.JLabel();
        p_name_label = new javax.swing.JLabel();
        p_id_label = new javax.swing.JLabel();
        cal = new de.wannawork.jcalendar.JCalendarPanel();
        ok_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sr_p_id = new javax.swing.JLabel();
        srch_id = new javax.swing.JTextField();
        sr_p_name = new javax.swing.JLabel();
        srch_name = new javax.swing.JTextField();
        srch_bttn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        p_name_exist = new javax.swing.JTextField();
        p_gender_exist = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        exist_p_name = new javax.swing.JLabel();
        p_age_exist = new javax.swing.JTextField();
        p_phno_exist = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        exist_p_age = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        p_addr_exist = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        presc_medicines = new javax.swing.JTextArea();
        near_medical = new javax.swing.JTextField();
        reset_exist_bttn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        unavl_medicines = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        prev_report = new javax.swing.JButton();
        prev_report1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        presc_medicines1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        add_report = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        filepath = new javax.swing.JTextField();
        patient_id_label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nm_working = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nm_phno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nm_email = new javax.swing.JTextField();
        nm_own_name = new javax.swing.JTextField();
        nm_loc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        nm_addr = new javax.swing.JTextArea();
        cb_m_name = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 229, 229));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1020, 515));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("LinkUs");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(" Doctor, Patient and Medical Store interconnection System");
        jLabel2.setToolTipText("");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linkus/logo.png"))); // NOI18N

        doc_label.setText("Doctor");

        abt_us.setText("About Us");
        abt_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abt_usActionPerformed(evt);
            }
        });

        log_out.setText("LogOut");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        p_id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_id_textActionPerformed(evt);
            }
        });
        p_id_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p_id_textKeyTyped(evt);
            }
        });

        p_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_name.setText("Patient Name");

        p_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_id.setText("Patient ID");

        p_name_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p_name_textKeyTyped(evt);
            }
        });

        p_addr_text.setColumns(20);
        p_addr_text.setRows(5);
        jScrollPane1.setViewportView(p_addr_text);

        p_addr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_addr.setText("Patient Address");

        p_email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_email.setText("Email");

        gender.add(p_male);
        p_male.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_male.setText("Male");
        p_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p_gender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_gender.setText("Gender");

        p_submit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        p_submit.setText("Submit");
        p_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_submitActionPerformed(evt);
            }
        });
        p_submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_submitKeyPressed(evt);
            }
        });

        gender.add(p_female);
        p_female.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_female.setText("Female");
        p_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p_email_label.setText("*");

        p_gender_label.setText("*");

        p_reset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        p_reset.setText("Reset");
        p_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_resetActionPerformed(evt);
            }
        });
        p_reset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p_resetKeyPressed(evt);
            }
        });

        p_dob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_dob.setText("Date of Birth");

        p_phno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_phno.setText("Phone no.");

        p_phno_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p_phno_textKeyTyped(evt);
            }
        });

        p_dob_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                p_dob_textFocusGained(evt);
            }
        });

        p_dob_label.setText("*");

        p_phno_label.setText("*");

        p_addr_label.setText("*");

        p_name_label.setText("*");

        p_id_label.setText("*");

        cal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                calStateChanged(evt);
            }
        });

        ok_btn.setText("OK");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(p_submit)
                        .addGap(103, 103, 103)
                        .addComponent(p_reset)
                        .addContainerGap(461, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(p_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p_addr, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(p_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(p_phno, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p_male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(p_female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(p_gender_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(425, 425, 425))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p_addr_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(419, 419, 419))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(p_name_text, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(p_id_text))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(p_email_text, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(p_phno_text))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p_phno_label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(p_email_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52)
                                        .addComponent(p_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ok_btn))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(p_dob_text, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(p_dob_label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(1, 1, 1)))))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_id_text)
                    .addComponent(p_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_name_text)
                    .addComponent(p_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p_addr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(71, 71, 71))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p_addr_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_phno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_phno_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_phno_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_email_text)
                            .addComponent(p_email_label))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(p_male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(p_female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(p_gender_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_dob_text)
                            .addComponent(p_dob_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ok_btn))
                        .addContainerGap())))
        );

        jTabbedPane2.addTab("Patient Registration", jPanel1);

        sr_p_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sr_p_id.setText("Search By Patient ID");

        srch_id.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                srch_idInputMethodTextChanged(evt);
            }
        });
        srch_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_idActionPerformed(evt);
            }
        });
        srch_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                srch_idKeyTyped(evt);
            }
        });

        sr_p_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sr_p_name.setText("Search By Patient Name");

        srch_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_nameActionPerformed(evt);
            }
        });

        srch_bttn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        srch_bttn.setText("Search");
        srch_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_bttnActionPerformed(evt);
            }
        });

        p_name_exist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_name_exist.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p_name_exist.setEnabled(false);

        p_gender_exist.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p_gender_exist.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Gender");

        exist_p_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exist_p_name.setText("Name");

        p_age_exist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_age_exist.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p_age_exist.setEnabled(false);

        p_phno_exist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_phno_exist.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p_phno_exist.setEnabled(false);
        p_phno_exist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_phno_existActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Phone No.");

        exist_p_age.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exist_p_age.setText("Patient Age");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Address");

        p_addr_exist.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p_addr_exist.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Nearest Medical");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Prescribed Medicines");

        presc_medicines.setColumns(20);
        presc_medicines.setRows(5);
        jScrollPane2.setViewportView(presc_medicines);

        near_medical.setEditable(false);

        reset_exist_bttn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        reset_exist_bttn.setText("Reset");
        reset_exist_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_exist_bttnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Unavailable Medicines");

        unavl_medicines.setEditable(false);
        unavl_medicines.setColumns(20);
        unavl_medicines.setRows(5);
        unavl_medicines.setEnabled(false);
        jScrollPane3.setViewportView(unavl_medicines);

        prev_report.setText("Previous Report");
        prev_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_reportActionPerformed(evt);
            }
        });

        prev_report1.setText("Add Report Image");
        prev_report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_report1ActionPerformed(evt);
            }
        });

        presc_medicines1.setColumns(20);
        presc_medicines1.setRows(5);
        jScrollPane6.setViewportView(presc_medicines1);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Problem Details");

        add_report.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        add_report.setText("Add Report");
        add_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_reportActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText(" ");

        filepath.setEditable(false);

        patient_id_label.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_report)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(near_medical, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(reset_exist_bttn)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(prev_report1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filepath)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(p_addr_exist))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(p_phno_exist))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(exist_p_age, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(p_age_exist, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(exist_p_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(p_name_exist)
                                            .addComponent(p_gender_exist, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(45, 45, 45)
                                .addComponent(prev_report, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sr_p_id, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(srch_id, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(sr_p_name))
                                    .addComponent(patient_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srch_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(srch_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srch_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sr_p_id, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(srch_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sr_p_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(srch_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patient_id_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exist_p_age, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_age_exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exist_p_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_name_exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p_phno_exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p_gender_exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prev_report)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_addr_exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(near_medical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prev_report1)
                            .addComponent(filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset_exist_bttn)
                            .addComponent(add_report)
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(65, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Existing Patient", jPanel2);

        nm_working.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Address");

        nm_phno.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Email Id");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Medical Name");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Phone No.");

        nm_email.setEnabled(false);

        nm_own_name.setEnabled(false);

        nm_loc.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Working");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText(" Locality");

        nm_addr.setEditable(false);
        nm_addr.setColumns(20);
        nm_addr.setRows(5);
        nm_addr.setEnabled(false);
        jScrollPane4.setViewportView(nm_addr);

        cb_m_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_m_nameItemStateChanged(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Owner Name");

        jLabel5.setText("Hidden username of medical");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nm_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cb_m_name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nm_own_name, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nm_phno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nm_email, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nm_working, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_m_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(nm_loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nm_working, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_own_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nearest Medical", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abt_us, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doc_label))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(abt_us, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(log_out)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jTabbedPane2))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void Text_reset(){
        p_id_text.setText("");
        p_name_text.setText("");
        p_phno_text.setText("");
        p_addr_text.setText("");
        p_city_text.setText("");
        p_email_text.setText("");
        p_dob_text.setText("");
        this.gender.clearSelection();
        this.revalidate();
        this.repaint();
    }
  
    public boolean check_id()
    {
        if(srch_id.getText().equals(""))
        {
            patient_id_label.setForeground(Color.red);
            patient_id_label.setText("Please enter ID first");
            return  false;
        }
        else
        {
            return true;
        }
    }
    public void label_reset()
    {
       
        p_id_label.setText("*");
        p_name_label.setText("*");
        p_phno_label.setText("*");
        p_email_label.setText("*");
        p_dob_label.setText("");
    }
    
    
    public int validation()
    {
        boolean flag=true;
        String pid = p_id_text.getText();
        String pname = p_name_text.getText();
        String phno = p_phno_text.getText();
        String email = p_email_text.getText();
        String city = p_city_text.getText();
        String dob = p_dob_text.getText();
        
        label_reset();
        
        //if all elements are blank
        if(pid.equals("")&&pname.equals("")&&phno.equals("")&&city.equals("")&&dob.equals(""))
           {
                 p_id_label.setText("Please Enter Valid Patient ID");
                 p_name_label.setText("Please Enter Valid Patient Name");
                 p_phno_label.setText("Please Enter Phone Number");
                 p_dob_label.setText("Please Enter Date of Birth");
                 flag=false;
           }
        
        if(pid.equals(""))
        {
                  p_id_label.setText("Please Enter Valid Patient ID");
                  flag=false;
        }
        
        //Patient Name Validation
        if(pname.equals(""))
        {
                 p_name_label.setText("Please Enter Valid Patient Name");
                 flag=false;
        }
        //Phone Number Validation
        if(phno.equals("")){
                p_phno_label.setText("Please Enter Phone Number");
                flag=false;
        }
        else{
                String pn=p_phno_text.getText();
                Pattern pattern2 = Pattern.compile("\\d{10}");
                Matcher matcher2 = pattern2.matcher(pn);
                
                                if (matcher2.matches()==false)
                                {
                                   p_phno_label.setText("Please Enter valid Phone Number");
                                   flag=false;
                                }
        }
        //Date Of Birth Validation
        if(dob.equals(""))
        {
           p_dob_label.setText("Please Enter Date of Birth");
           flag=false;
        }
        else
        {
            Pattern pattern4 =Pattern.compile("([0-9]{2})/([0-9]{2})/([0-9]{4})");
            Matcher matcher4 =pattern4.matcher(p_dob_text.getText());
            if (matcher4.matches()==false)
            {
                p_dob_label.setText("InValid Dob ");
                flag=false;
            }
            
        }
        //Gender Validation
        
        if(flag)
            return 1; 
        else
            return 0;
    }
    
    private void abt_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abt_usActionPerformed
         new aboutus("Home").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_abt_usActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_log_outActionPerformed

    private void srch_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srch_idKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_srch_idKeyTyped

    private void srch_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_bttnActionPerformed
        if(check_id()||!srch_name.getText().equals(""))
        {
            try{
                    MongoClient mc;
                    mc = new MongoClient("localhost",27017);
                    DB db = mc.getDB("linkus");
                    DBCollection coll = db.getCollection("patient_details");
                    BasicDBObject obj = new BasicDBObject();
                    if(srch_id.getText().equals(""))
                        obj.put("p_name",srch_name.getText());
                    else
                        obj.put("p_id", srch_id.getText());

                    DBCursor cursor = coll.find(obj);
                    while(cursor.hasNext())
                    {
                        LocalDate today = LocalDate.now();
                        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("dd/MM/yyyy",Locale.ENGLISH);
                        LocalDate birthday = LocalDate.parse((String)cursor.next().get("p_dob"), dtf);
                        Period p = Period.between(birthday, today);
                        srch_id.setText((String)cursor.curr().get("p_id"));
                        p_age_exist.setText(String.valueOf(p.getYears()));
                        p_name_exist.setText((String)cursor.curr().get("p_name"));
                        p_addr_exist.setText((String)cursor.curr().get("p_addr"));
                        p_gender_exist.setText((String)cursor.curr().get("p_gender"));
                        p_phno_exist.setText((String)cursor.curr().get("p_phno"));
                        Absclass.p_id=srch_id.getText();
                    }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,"Your database server is not responding ...","Error",1);
                System.out.println(e.getMessage());
            };
        }
    }//GEN-LAST:event_srch_bttnActionPerformed

    private void p_phno_existActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_phno_existActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_phno_existActionPerformed

    private void reset_exist_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_exist_bttnActionPerformed
        Text_reset_exist();
    }//GEN-LAST:event_reset_exist_bttnActionPerformed

    private void prev_report1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_report1ActionPerformed
        //new addfile().setVisible(true);
        //this.setVisible(false);
        if(check_id())
        {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File file=chooser.getSelectedFile();
            String fname=file.getAbsolutePath();
            filepath.setText(fname);
        }
    }//GEN-LAST:event_prev_report1ActionPerformed

    private void p_dob_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p_dob_textFocusGained
        // TODO add your handling code here:
        cal.setVisible(true);
        ok_btn.setVisible(true);
    }//GEN-LAST:event_p_dob_textFocusGained

    private void p_phno_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_phno_textKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_p_phno_textKeyTyped

    private void p_resetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_resetKeyPressed

    }//GEN-LAST:event_p_resetKeyPressed

    private void p_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_resetActionPerformed
        if(evt.getSource() == p_reset)
        {
            label_reset();
            Text_reset();

        }
    }//GEN-LAST:event_p_resetActionPerformed

    private void p_submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_submitKeyPressed

    }//GEN-LAST:event_p_submitKeyPressed

    private void p_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_submitActionPerformed
        label_reset();
        int a=validation();
        if(a==1)
        {
            try
            {
                MongoClient mc = new MongoClient("localhost",27017);
                DB db = mc.getDB("linkus");
                DBCollection coll = db.getCollection("patient_details");
                DBCollection coll2=db.getCollection("patient_details");
                BasicDBObject obj2 = new BasicDBObject();
                obj2.put("p_id", p_id_text.getText());
                    DBCursor cursor = coll.find(obj2);
                    while(cursor.hasNext())
                    {
                        flag=true;
                        p_id_label.setVisible(true);
                        p_id_label.setForeground(Color.red);
                        p_id_label.setText("Patienr ID already exist ...");
                    }
            if(!flag){
                BasicDBObject obj = new BasicDBObject("p_id",p_id_text.getText());
                obj.append("p_name",p_name_text.getText());
                obj.append("p_addr",p_addr_text.getText());
                obj.append("p_city",p_city_text.getText());
                obj.append("p_phno",p_phno_text.getText());
                obj.append("p_email",p_email_text.getText());
                if(p_male.isSelected())
                obj.append("p_gender","male");
                else if(p_female.isSelected())
                obj.append("p_gender","female");
                obj.append("p_dob",p_dob_text.getText());
                obj.append("p_by_doc",Absclass.username);
                coll.insert(obj);
                JOptionPane.showMessageDialog(this,"Patient Added Successfully...");
                if(evt.getSource() == p_reset)
                {
                    label_reset();
                    Text_reset();
                }
            }
            }
            catch(Exception e){

                    JOptionPane.showMessageDialog(this,"Your database server is not responding ...","Error",1);
            };
        }
    }//GEN-LAST:event_p_submitActionPerformed

    private void p_name_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_name_textKeyTyped

        char c = evt.getKeyChar();
        if(!(Character.isLetter(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_SPACE)||(c==evt.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_p_name_textKeyTyped

    private void p_id_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_id_textKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==evt.VK_BACK_SPACE)||(c==evt.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_p_id_textKeyTyped

    private void p_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_id_textActionPerformed

    private void calStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_calStateChanged
        // TODO add your handling code here:
        Date date = this.cal.getDate();
        SimpleDateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        String format = df.format(date);
        p_dob_text.setText(format);
    }//GEN-LAST:event_calStateChanged

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        // TODO add your handling code here:
        Date date = this.cal.getDate();
        SimpleDateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        String format = df.format(date);
        p_dob_text.setText(format);
        this.cal.setVisible(false);
        this.ok_btn.setVisible(false);
    }//GEN-LAST:event_ok_btnActionPerformed

    private void add_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_reportActionPerformed
        // TODO add your handling code here:
        String fname=null;
        if(presc_medicines.getText().equals("")||presc_medicines1.getText().equals(""))
        {
            jLabel4.setText("* fields are mandetory");
        }
        else if(srch_id.getText().equals(""))
        {
            jLabel4.setText("First Search for the patient");
        }
        else if(filepath.getText().equals(""))
        {
            jLabel4.setText("Add report image");
        }
        else if(cb_m_name.getSelectedItem().equals("--select--"))
        {
            jLabel4.setText("Please select nearest medical ....");
        }
        else
        {
            try
            {
                MongoClient mc;
                mc = new MongoClient("localhost",27017);
                DB db = mc.getDB("linkus");
                DBCollection coll = db.getCollection("patient_reports");
                DBCollection coll3=db.getCollection(jLabel5.getText());
                BasicDBObject obj = new BasicDBObject();
                BasicDBObject medi = new BasicDBObject();                
                try
                {
                    DBCollection coll2 = db.getCollection("photo.files");
                    BasicDBObject obj3 = new BasicDBObject();
                    obj3.put("$set",new BasicDBObject("p_id", srch_id.getText()));
                    GridFS photo= new GridFS(db,"photo");
                    File f = new File(filepath.getText());
                    fname=f.getName();
                    GridFSInputFile gfsfile = photo.createFile(f);
                    gfsfile.setFilename(f.getName());
                    gfsfile.save();
                    BasicDBObject obj2 = new BasicDBObject("filename", f.getName());
                    coll2.update(obj2, obj3);
                }
                catch(Exception e){}
                
                obj.put("p_id", srch_id.getText());
                obj.append("p_name", p_name_exist.getText());
                obj.append("p_gender", p_gender_exist.getText());
                obj.append("p_prescribed_medi", presc_medicines.getText());
                obj.append("p_prob_details", presc_medicines1.getText());
                obj.append("p_by_doc", Absclass.username);
                obj.append("report_img", fname);
                coll.insert(obj);
                medi.put("prescrip", presc_medicines.getText());
                medi.append("stat","pending");
                medi.append("pname",p_name_exist.getText());
                medi.append("pid",srch_id.getText());
                coll3.insert(medi);
                JOptionPane.showMessageDialog(this,"Patient report added successfully...");
            }
            catch (UnknownHostException ex) {
                Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Your database server is not responding ...","Error",1);
            }            
        }
    }//GEN-LAST:event_add_reportActionPerformed

    private void srch_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_idActionPerformed
        // TODO add your handling code here:
        srch_bttn.doClick();
    }//GEN-LAST:event_srch_idActionPerformed

    private void srch_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_nameActionPerformed
        // TODO add your handling code here:
        srch_bttn.doClick();
    }//GEN-LAST:event_srch_nameActionPerformed

    private void prev_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_reportActionPerformed
        // TODO add your handling code here:
        new reports().setVisible(true);
    }//GEN-LAST:event_prev_reportActionPerformed

    private void srch_idInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_srch_idInputMethodTextChanged
        // TODO add your handling code here:
        patient_id_label.setText(null);
    }//GEN-LAST:event_srch_idInputMethodTextChanged

    private void cb_m_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_m_nameItemStateChanged
        // TODO add your handling code here:
        try {
                MongoClient mc;
                mc = new MongoClient("localhost",27017);
                DB db = mc.getDB("linkus");
                DBCollection coll = db.getCollection("medi_details");
                BasicDBObject obj = new BasicDBObject("medi_name",cb_m_name.getSelectedItem().toString());
                DBCursor cursor = coll.find(obj);                
                nm_loc.setText(cursor.next().get("medi_loc").toString());
                nm_addr.setText(cursor.curr().get("medi_add").toString());
                nm_email.setText(cursor.curr().get("email").toString());
                nm_own_name.setText(cursor.curr().get("medi_own").toString());
                nm_working.setText(cursor.curr().get("mstat").toString());
                nm_phno.setText(cursor.curr().get("ph_no").toString());
                jLabel5.setText(cursor.curr().get("user_name").toString());
                near_medical.setText(cursor.curr().get("medi_name").toString());
                unavl_medicines.setText(cursor.curr().get("unavl_medi").toString());
       }
        catch(Exception e){
        }
        
    }//GEN-LAST:event_cb_m_nameItemStateChanged

    public void Text_reset_exist()
    {
        srch_id.setText("");
        srch_name.setText("");
        p_age_exist.setText("");
        p_phno_exist.setText("");
        p_addr_exist.setText("");
        p_name_exist.setText("");
        p_gender_exist.setText("");
        near_medical.setText("");
        unavl_medicines.setText("");
        presc_medicines.setText("");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abt_us;
    private javax.swing.JButton add_report;
    private de.wannawork.jcalendar.JCalendarPanel cal;
    private javax.swing.JComboBox cb_m_name;
    private javax.swing.JLabel doc_label;
    private javax.swing.JLabel exist_p_age;
    private javax.swing.JLabel exist_p_name;
    private javax.swing.JTextField filepath;
    private javax.swing.ButtonGroup gender;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton log_out;
    private javax.swing.JTextField near_medical;
    private javax.swing.JTextArea nm_addr;
    private javax.swing.JTextField nm_email;
    private javax.swing.JTextField nm_loc;
    private javax.swing.JTextField nm_own_name;
    private javax.swing.JTextField nm_phno;
    private javax.swing.JTextField nm_working;
    private javax.swing.JButton ok_btn;
    private javax.swing.JLabel p_addr;
    private javax.swing.JTextField p_addr_exist;
    private javax.swing.JLabel p_addr_label;
    private javax.swing.JTextArea p_addr_text;
    private javax.swing.JTextField p_age_exist;
    private javax.swing.JTextField p_city_text;
    private javax.swing.JLabel p_dob;
    private javax.swing.JLabel p_dob_label;
    private javax.swing.JTextField p_dob_text;
    private javax.swing.JLabel p_email;
    private javax.swing.JLabel p_email_label;
    private javax.swing.JTextField p_email_text;
    private javax.swing.JRadioButton p_female;
    private javax.swing.JLabel p_gender;
    private javax.swing.JTextField p_gender_exist;
    private javax.swing.JLabel p_gender_label;
    private javax.swing.JLabel p_id;
    private javax.swing.JLabel p_id_label;
    private javax.swing.JTextField p_id_text;
    private javax.swing.JRadioButton p_male;
    private javax.swing.JLabel p_name;
    private javax.swing.JTextField p_name_exist;
    private javax.swing.JLabel p_name_label;
    private javax.swing.JTextField p_name_text;
    private javax.swing.JLabel p_phno;
    private javax.swing.JTextField p_phno_exist;
    private javax.swing.JLabel p_phno_label;
    private javax.swing.JTextField p_phno_text;
    private javax.swing.JButton p_reset;
    private javax.swing.JButton p_submit;
    private javax.swing.JLabel patient_id_label;
    private javax.swing.JTextArea presc_medicines;
    private javax.swing.JTextArea presc_medicines1;
    private javax.swing.JButton prev_report;
    private javax.swing.JButton prev_report1;
    private javax.swing.JButton reset_exist_bttn;
    private javax.swing.JLabel sr_p_id;
    private javax.swing.JLabel sr_p_name;
    private javax.swing.JButton srch_bttn;
    private javax.swing.JTextField srch_id;
    private javax.swing.JTextField srch_name;
    private javax.swing.JTextArea unavl_medicines;
    // End of variables declaration//GEN-END:variables

    private void near_medical() {
        try {
                MongoClient mc;
                mc = new MongoClient("localhost",27017);
                DB db = mc.getDB("linkus");
                DBCollection coll = db.getCollection("doc_details");
                BasicDBObject obj = new BasicDBObject("user_name",Absclass.username);
                DBCursor cursor = coll.find(obj);                
                String doc_loc=(String) cursor.next().get("clinic_loc");
                DBCollection coll2 = db.getCollection("medi_details");
                BasicDBObject obj2 = new BasicDBObject("medi_loc",doc_loc);
                DBCursor cursor2 = coll2.find(obj2);
                DefaultComboBoxModel model = (DefaultComboBoxModel) cb_m_name.getModel();
                model.addElement("--select--");
                while(cursor2.hasNext())
                {
                    model.addElement(cursor2.next().get("medi_name").toString());
                }
        }
        catch(Exception e){
        }
    }
}
